name: Build XL firmware

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-xl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # >>> Klucz: używamy oficjalnego build.py zamiast surowego cmake <<<
      - name: Build XL release (boot)
        run: |
          python utils/build.py --preset xl --build-type release --final

      - name: List products
        run: ls -R build/products || true

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: xl-firmware
          path: |
            build/products/**/*.bbf
            build/products/**/*.bin
